# Generated by Django 5.2.5 on 2025-08-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=20)),
            ],
        ),
    ]
